---
#===============================================#
# Informações principais
#===============================================#
instituicao: Instituto Federal de Sergipe
author: Reinan Gabriel Dos Santos Souza
title: 'Introdução à Profissão de Físico Teórico'
local: Lagarto - SE
date: '2023'
titulacao: Bacharel
curso: Sistemas de informação
programa: Programa de Pós-Graduação em 2023
area_de_concentracao: ''
linha_de_pesquisa: 'Física teórica'
coorientador: ''
orientador: ''
avaliador2: ''
aprovacao_dia: '1'
avaliador1: ''
avaliador3: ''
#===============================================#
# Configurações de textos
#===============================================#
resumo: '@import(pages/resumo.md)'
abstract_texto: '@import(pages/abstract.md)'
proposito: '@import(pages/proposito.md)'
agradecimentos: '@import(pages/agradecimentos.md)'
resumen: ''
resume: ''
dedicatoria: ''
epigrafe: ''
capa_pdf_caminho: ''
#===============================================#
# Informações importantes
#===============================================#
siglas:
  - s: USP
    d: Universidade de São Paulo
  - s: UNICAMP
    d: Universidade Estadual de Campinas
  - s: INPE
    d: Instituto Nacional de Pesquisas Espaciais
  - s: INFN
    d: Instituto Nacional de Física Nuclear
  - s: CBPF
    d: Centro Brasileiro de Pesquisas Físicas
  - s: IFT-UNESP
    d: Instituto de Física Teórica da Universidade Estadual Paulista
  - s: IFUSP
    d: Instituto de Física da Universidade de São Paulo
  - s: IF-UFRJ
    d: Instituto de Física da Universidade Federal do Rio de Janeiro
  - s: IFGW-UNICAMP
    d: Instituto de Física Gleb Wataghin da Universidade Estadual de Campinas
  - s: CCNH-UFABC
    d: Centro de Ciências Naturais e Humanas da Universidade Federal do ABC
simbolos:
graduacao: true
especializacao: false
mestrado: false
doutorado: false
tipo_do_trabalho: "Artigo acadêmico"
incluir_ficha_catalografica: false
folha_de_aprovacao: false
projeto: true
apendices: false
anexos: false
errata: false
referencias_sistema: alf
lista_ilustracoes: false
lista_quadros: false
lista_tabelas: false
referencias_caminho: config/referencias.bib
palavras_chave: 'Física teórica, Formação acadêmica, Carreira em física, Pesquisa científica, Ensino de física, Cientistas brasileiros e Físicos teóricos brasileiros'
keywords: 'Theoretical physics, Academic training, Career in physics, Scientific research, Physics teaching, Brazilian scientists and Brazilian theoretical physicists'
palabras_clave: ''
mots_cles: ''
#===============================================#
# Configurações para o limarka-render-html
# Link: https://github.com/ReinanHS/limarka-render-html
#===============================================#
page_render:
  published_time: '2023-09-11T18:26:24-03:00'
  instituicao_website: 'https://www.ifs.edu.br/'
  social_networks:
    facebook: reinangabriel
    instagram: reinanhs
    twitter: ReinanGabriel9
    github: reinanhs
  pages_render:
    - resumo.md
    - agradecimentos.md
  files_type:
    - pdf
    - tex
    - bib
  files_map:
    - "xxx-trabalho-academico.tex:trabalho-academico.tex"
    - "xxx-referencias.bib:referencias.bib"
---