name: Container Workflow

on:
  push:
    branches: [ "master" ]
   
jobs:
  build-limarka:
    runs-on: ubuntu-latest
    container:
      image: docker://reinanhs/limarka-help:1.0.0

    steps:
      - uses: actions/checkout@v3

      - name: Run Commands
        run: |
          limarka check
          limarka --version
          limarka-help
          mkdir -p dist
          mv build/* ./dist/
          ls ./dist

      - name: Archive limarka artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-limarka
          path: dist
          retention-days: 1

  build-marp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure build dir exists
        run: mkdir -p build

      - name: Copy images directory (if exists)
        run: if [[ -d imagens ]]; then cp -R imagens build/imagens; fi

      - name: Copy videos directory (if exists)
        run: if [[ -d videos ]]; then cp -R videos build/videos; fi

      - name: Dowload theme
        run: wget https://raw.githubusercontent.com/reinanhs/marp-theme-academic/main/themes/academic.css

      - name: Marp Build (README)
        uses: docker://marpteam/marp-cli:v3.3.0
        with:
          args: slide-deck.md --theme academic.css -o build/slide.html
        env:
          MARP_USER: root:root
          LANG: "pt_BR.UTF-8"

      - name: Marp Build (README.pdf)
        uses: docker://marpteam/marp-cli:v3.3.0
        with:
          args: slide-deck.md --theme academic.css --allow-local-files -o build/README.pdf
        env:
          MARP_USER: root:root
          LANG: "pt_BR.UTF-8"

      - name: Marp Build (README.pptx)
        uses: docker://marpteam/marp-cli:v3.3.0
        with:
          args: slide-deck.md --theme academic.css --allow-local-files -o build/README.pptx
        env:
          MARP_USER: root:root
          LANG: "pt_BR.UTF-8"

      - name: Archive marp artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-marp
          path: build
          retention-days: 1

  deploy:
    needs: [build-limarka, build-marp]
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Download build Limark
        uses: actions/download-artifact@v3
        with:
          name: dist-limarka
          path: build-limarka

      - name: Download build Marp
        uses: actions/download-artifact@v3
        with:
          name: dist-marp
          path: build

      - name: Move file
        run: mv ./build-limarka/xxx-trabalho-academico.pdf ./build/texto-sobre-tema.pdf

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
          clean-exclude: pr-preview/
